# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e8b1710d75a1114f40d239e0765e3686f31765cdee18cc9460babd0a3f8f237d55d250ae899f456d35378bbcad6b9e7c5606c42c41f4b37fedd27969a144208

test:
  secret_key_base: 2183148d7c6b063ddebdc470c4f8b3da59f25d35a50a2d8f8c63a8490dc16c971bbfd053e9023e7ac4b28fb2e597a12bc13b6b70f77fe7966c21a450ca9caac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
